# Generated by Django 3.0.6 on 2020-05-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='to_show',
            field=models.BooleanField(default=True),
        ),
    ]
