# Generated by Django 3.0.6 on 2020-06-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200601_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('to_publish', models.BooleanField(default=False)),
            ],
        ),
    ]
